### ISSUE TITLE
trouble with the rpi driver type

### ISSUE THREAD

**Issue by RedSquid06** [robertklep/homebridge-klikaanklikuit#25]
Yesterday i have set up my kaku system with the homebridge. but when i start homebridge i get an error. 

'[2018-5-12 12:57:52] Loading 1 platforms...
[2018-5-12 12:57:52] [KlikAanKlikUit] Initializing KlikAanKlikUit platform...
/usr/lib/node_modules/homebridge-klikaanklikuit/index.js:26
      throw Error(`Unable to load driver '${ driver.type }': ${ e.message }`);
      ^

Error: Unable to load driver 'rpi': Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/build/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/build/Debug/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/build/Release/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/out/Debug/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/Debug/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/out/Release/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/Release/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/build/default/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/compiled/8.11.1/linux/arm/rpio.node
    at new KaKuPlatform (/usr/lib/node_modules/homebridge-klikaanklikuit/index.js:26:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:304:32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3'

after this homebridge shutsdown. 
Does anyone knows whats wrong?

here is my config file:

{
        "bridge": {
                "name": "Homebridge",
                "username": "...",
                "port": ---,
                "pin": "---"
        },

        "platforms": [{
                "platform": "Nest",
                "token": "...",
                "clientId": "..",
                "clientSecret": "...",
                "code": "..."
        }, {
                "platform": "KlikAanKlikUit",
                "driver": {
                        "type": "rpi",
                        "pin": 8
                }
        }],

        "accessories": [{
                "name"     : "huiskamerlamp",
                "type"     : "outlet",
                "address"  : "A",
                "device"   : "1"
                },
                {
                "name"     : "sierlamp",
                "type"     : "Outlet",
                "address"  : "A",
                "device"   : "3"
                },
                {
                "name"     : "dimlamp",
                "type"     : "Outlet",
                "address"  : "A",
                "device"   : "4"
                }
        ]
}

**Comment by robertklep** [comment]
This looks very similar to #22. If possible, try and see if you can downgrade to Node v6 and see if it works again.

**Comment by RedSquid06** [comment]
Do i have to remove and reinstall homebridge? and klikaanklikuit plugin?

**Comment by robertklep** [comment]
You may have to reinstall both if you're using a different version of Node.js.

**Comment by RedSquid06** [comment]
now i got an other error:

5/12/2018, 2:03:33 PM] [KlikAanKlikUit] Initializing KlikAanKlikUit platform...
[5/12/2018, 2:03:33 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] using driver 'rpi'
[5/12/2018, 2:03:33 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] initialized RPi driver (pin 8)
[5/12/2018, 2:03:33 PM] Loading 3 accessories...
/usr/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:50:11)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3

**Comment by robertklep** [comment]
This could be caused by some left-over files in the Homebridge directory (`~/.homebridge`). Try removing everything apart from the `config.json` file in that directory.

**Comment by RedSquid06** [comment]
still not working. i removed everything. there was nothing left installed it again and still the same error.
Also the ~/.homebridge folder.

[5/12/2018, 2:23:51 PM] Loaded plugin: homebridge-klikaanklikuit
[5/12/2018, 2:23:51 PM] Registering platform 'homebridge-klikaanklikuit.KlikAanKlikUit'
[5/12/2018, 2:23:51 PM] ---
[5/12/2018, 2:23:51 PM] Loaded config.json with 3 accessories and 1 platforms.
[5/12/2018, 2:23:51 PM] ---
[5/12/2018, 2:23:51 PM] Loading 1 platforms...
[5/12/2018, 2:23:51 PM] [KlikAanKlikUit] Initializing KlikAanKlikUit platform...
[5/12/2018, 2:23:51 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] using driver 'rpi'
[5/12/2018, 2:23:51 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] initialized RPi driver (pin 8)
[5/12/2018, 2:23:51 PM] Loading 3 accessories...
/usr/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:50:11)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

**Comment by robertklep** [comment]
According to a few issues, this points to an incorrect `config.json` file:
* https://github.com/nfarina/homebridge/issues/756
* https://github.com/nfarina/homebridge/issues/1776

**Comment by RedSquid06** [comment]
can't seem to figure it out... thanks anyway!

**Comment by robertklep** [comment]
Feel free to post your config file here so I can take a look at it 😄

**Comment by RedSquid06** [comment]
well i also installed the nest on to my homebridge and the nest plugin needs the newer verion of nodejs. So if that whas the problem, it's no use. I'm trying now thrue PiLights.

**Comment by robertklep** [comment]
I'm not sure what's causing the problem with `rpio`, I've tried with Node.js 8.11.1 and it seems to work just fine.

What could have happened is that when you installed `homebridge-klikaanklikuit`, an error was being thrown that you may have overlooked.

So my $0.02: install Node.js v8 again, try reinstalling `homebridge-klikaanklikuit`, and check for any errors.

**Comment by robertklep** [comment]
FWIW, there's a solution mentioned in #27 (manually rebuild the underlying native modules).
